### PR TITLE
Awk rewrite

### PR DESCRIPTION
**Pull request by Screwtapello**
This PR replaces the C helper tool with an Awk script that does the same thing. This makes the plugin usable immediately after installation, instead of requiring a separate compilation step. The result does feel perhaps a tad slower on my 4333.33-bogomips Celeron laptop, but still pretty smooth.

This PR does not include the rendering changes (selection count, different faces) from my previous attempt at rewriting the helper in awk, but it *does* include the change that calculates the window height based on `%val{window_range}` rather than `%val{window_height}`, because it was easy enough to do, and it fit neatly in with the command-line-argument refactoring.

I was impressed at how easy it was to port the C code to Awk. The main differences turned out to be:

- no variable types, which in one place meant calling `int()` explicitly instead of assigning to an integer variable
- no local variables, but awk *does* have optional arguments, so the convention is to define functions with the intended parameters, then leave a little space, then the local variables
- `split()` is a heck of a lot nicer than `strtok()`
- string concatenation is just adjacency (`"Label 1:" var1 ", Label 2:" var2`)
- no bitwise operations, so I changed `|=` to `+=` in the one place it occurred
- no semicolons

### CODE REVIEW

**Comment by danr** [comment]
Awk looks really pleasant to use for this!

**Comment by sawdust-and-diamonds** [comment]
I thought I'd accepted this commit. Oh, well! Life's been chaotic, lately. Let's give this a playtest and then go for it.

**Comment by caksoylar** [comment]
I found a difference w.r.t. highlighting, which I believe isn't due to the `window_range` fix. Here is a (pretty specific, sorry) reproducer:
```sh
tput lines  # outputs 45, so that `%val{window_height}` is 44 in kak
cd src/kakoune  # mawww/kakoune repo
kak -n -e 'source ~/.config/kak/plugins/scrollbar.kak/scrollbar.kak; scrollbar-enable; exec "<percent>sKeyList<ret>"' src/keys.cc
```

`main` branch:
image

With the diff from this PR applied:
image

**Comment by Screwtapello** [comment]
Thanks for the report! The original C code represented the scrollbar with a bitfield of flags per line - one flag for "is this section of the buffer visible" and another for "are there any selections in this section of the buffer". Predictably, it used bitwise operations to set each flag individually.

AWK doesn't have bitwise operations, so I replaced C's `|=` with `+=` since that *also* sets the given flag. Unfortunately, I forgot that one section of the buffer might have multiple selections: `1 | 2` is the same as `1 + 2` but it's quite different from `1 + 2 + 2`. As a result, when a section of the bufffer had two or more selections, that line of the scrollbar would not render at all. As a result, I've changed that section of the code to spell out the bit-setting with an `if` statement:

https://github.com/Screwtapello/scrollbar.kak/blob/a28548278dcafccd73bdfda278232a50355f8789/scrollbar.kak#L68-L72

I wrote a fuzzer to randomly generate selection-sets and window-geometries and feed them into the AWK and C implementations, and no other differences showed up, so I'm pretty confident in this PR now.

**Comment by caksoylar** [comment]
Thanks, glad you could get it sorted out! The new version works great for me so far.

> I wrote a fuzzer to randomly generate selection-sets and window-geometries and feed them into the AWK and C implementations, and no other differences showed up, so I'm pretty confident in this PR now.

I would not have thought of doing that, sounds like a good approach 😄

**Comment by vbauerster** [comment]
@Screwtapello
Is `scrolloff` option accounted? I'm asking because with `scrolloff 5,1` for example, scrollbar shows 4 selections but in fact there are 3 only visible, see on screenshot below:
Screen Shot 2021-06-21 at 15 05 05

**Comment by Screwtapello** [comment]
The scrollbar logic uses Kakoune's `%val{window_range}` expansion, which I trust incorporates `scrolloff` if it needs to (although I haven't verified it myself).

However, I think the real cause of the problem you describe is rounding errors. The screenshot you posted is (I think) 39 lines high, and the scrollbar thumb covers 12 lines, or 3.25 buffer lines per block. Thus, selections up to 3 or 4 buffer-lines below the bottom of the window might be included in the last block of the scroll thumb.

Probably somebody could pick through the mathematics of this plugin and guarantee that, say, any cursor in the visible portion of the buffer will always be highlighted in the scroll thumb, that the scroll thumb will always touch the top or bottom of the window when the cursor is at the top or bottom of the buffer, etc. etc. I don't think anybody's done that, though, and this PR is specifically designed to replicate the behaviour of the existing C code as closely as possible rather than improving on it.

**Comment by vbauerster** [comment]
I'm pretty satisfied with this PR, so thank you for this PR. Hope it's going to be merged.

ping @sawdust-and-diamonds

**Pull request merged**
